autofetch_sources: True

networks:
  default: mainnet-fork

dotenv: .env

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0  # this is latest for sol v0.6
    - smartcontractkit/chainlink@1.6.0
    - Uniswap/v3-core@1.0.0
    - Uniswap/v3-periphery@1.3.0

compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
          - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0"
          - "@chainlink=smartcontractkit/chainlink@1.6.0"
          - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
          - "@uniswap/v3-periphery=Uniswap/v3-periphery@1.3.0"
