name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: py-actions/py-dependency-install@v4
      - uses: psf/black@stable
          with:
            python-version: 3.9
            version: "21.9b0"
